default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "osmanjalloh") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  <% if ENV["DB_HOST"].present? %>
  host: <%= ENV["DB_HOST"] %>
  <% end %>

development:
  <<: *default
  database: techsa_development

test:
  <<: *default
  database: techsa_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
