source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.0"

gem "rails", "~> 7.1"
gem "pg", "~> 1.1"
gem "puma", "~> 6.0"
gem "rack-cors"
gem "devise"
gem "devise-jwt"
gem "bcrypt", "~> 3.1.7"

group :development, :test do
  gem "debug", platforms: %i[mri mingw x64_mingw]
end

group :development do
  gem "rubocop-rails-omakase", require: false
end
